{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "base.database" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_PASSWORD: {{ default (include "base.database.encryptedPassword" .) (print .Values.database.password | b64enc | quote) }}
{{- end -}}
