{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.database" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  {{- with .Values.database.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 5432
  selector:
    {{- include "base.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end -}}
