{{- if and .Values.temporal.enabled .Values.temporal.server.enabled }}
{{- range $store := (list "default" "visibility") }}
{{- $secretName := (printf "%s-%s-store" (include "base.temporal" $) $store) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
type: Opaque
data:
  password: {{ template "base.database.encryptedPassword" $ }}
{{- end }}
{{- end }}
